spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prova
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG